linters:
  enable-all: true
  disable:
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - gomnd
    - lll
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

    #
    # Disabled because of generics:
    #
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

    #
    # Disabled because deprecated:
    #
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - scopelint
    - varcheck

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
  gofumpt:
    extra-rules: true

issues:
  exclude-rules:
    path: types/execution.go
    linters:
      - tagliatelle
