linters:
  enable-all: true
  disable:
    - depguard
    - dupl
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - inamedparam
    - intrange
    - lll
    - mnd
    - musttag
    - nlreturn
    - nonamedreturns
    - paralleltest
    - perfsprint
    - revive
    - tenv
    - testifylint
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

    #
    # Disabled because of generics:
    #
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

linters-settings:
  cyclop:
    max-complexity: 20
  tagliatelle:
    case:
      rules:
        json: snake
  gofumpt:
    extra-rules: true
  gomoddirectives:
    replace-allow-list:
      - github.com/attestantio/go-builder-client
      - github.com/attestantio/go-eth2-client
