linters:
  enable-all: true
  disable:
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - gomnd
    - lll
    - musttag
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

    #
    # Disabled because of generics:
    #
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

    #
    # Disabled because deprecated:
    #
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - scopelint
    - varcheck

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
  gofumpt:
    extra-rules: true
  gomoddirectives:
    replace-allow-list:
      # TODO: remove when https://github.com/attestantio/go-builder-client/pull/12 is merged
      - github.com/attestantio/go-builder-client
