name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run unit tests and generate the coverage report
        run: make test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@v0.7.0

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.6.0

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5

      - name: Lint
        run: make lint

      - name: Ensure go mod tidy runs without changes
        run: go mod tidy && git diff-index --quiet HEAD

  fuzz:
    name: Fuzz
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Fuzz each test for one second
        run: TERM=xterm FUZZTIME=1s make fuzz
